# Generated by Django 5.2.1 on 2025-06-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tg_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
