services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./subs_store:/subs_store
    environment:
      - DB_HOST=postgres
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

    command: "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - postgres

  postgres:
    image: postgres:17.5-alpine
    container_name: my-postgres
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

  pgadmin:
    image: elestio/pgadmin
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@google.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres