services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./subs_store:/subs_store
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

    command: >
      sh -c "(python manage.py runserver 0.0.0.0:8000 &) &&
                python bot_tg.py"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17.5-alpine
    container_name: my-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: elestio/pgadmin
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres