# Generated by Django 5.2.1 on 2025-06-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(max_length=50, verbose_name='Товар')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('date_order', models.DateField(auto_now_add=True, verbose_name='Дата покупки')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
